[package]
name = "kalosm-chat"
version = "0.1.0"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
edition = "2021"

[dependencies]
comrak = "0.40.0"
dioxus = { version = "0.7", features = ["router"] }
reqwest = "0.12.12"
kalosm-llama = { path = "/Users/evanalmloff/Desktop/Github/floneum/models/kalosm-llama" }
getrandom = { version = "0.3", features = ["wasm_js"] }
wasm-timer = "0.2.5"
tracing = "0.1.44"

[features]
web = ["dioxus/web"]
desktop = ["kalosm-llama/tokio", "dioxus/desktop"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
