[package]
name = "kalosm-chat"
version = "0.1.0"
authors = ["jermsam <ssali@jitpomi.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.0-alpha.3", features = ["router"] }

# Only include native feature when targeting iOS
[target.'cfg(target_os = "ios")'.dependencies.dioxus]
version = "0.7.0-alpha.3"
features = [
    "router",
    # "native",
    ]
    
# iOS-specific dependencies
[target.'cfg(target_os = "ios")'.dependencies]
metal = "0.32.0"

[features]
default = ["mobile"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
