[package]
name = "kalosm-chat"
version = "0.1.0"
authors = ["jermsam <ssali@jitpomi.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.40.0"
dioxus = { version = "0.7.0-alpha.3", features = ["router"] }
serde = { version = "1.0.219", features = ["derive"] }
#kalosm = { version = "0.4.0", default-features = false, features = ["language","llama"] }

# Only include native feature for iOS and macOS
[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies.dioxus]
version = "0.7.0-alpha.3"
features = [
    "router",
     "native",
    ]
    
# iOS and macOS-specific dependencies
[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
metal = "0.32.0"
kalosm = { version = "0.4.0", features = ["language","metal"] }

[features]
default = ["mobile"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
