name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: dioxuslabs/dioxus-ci/.github/workflows/check.yml@v0.1.0
    with:
      all-features: false
      no-default-features: true
      features: web

  test:
    uses: dioxuslabs/dioxus-ci/.github/workflows/test.yml@v0.1.0
    with:
      no-default-features: true
      features: web

  fmt:
    uses: dioxuslabs/dioxus-ci/.github/workflows/fmt.yml@v0.1.0

  docs:
    uses: dioxuslabs/dioxus-ci/.github/workflows/docs.yml@v0.1.0
    with:
      all-features: false
      no-default-features: true
      features: web

  clippy:
    uses: dioxuslabs/dioxus-ci/.github/workflows/clippy.yml@v0.1.0
    with:
      all-features: false
      no-default-features: true
      features: web
